accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django Admin
    path('admin/', admin.site.urls),

    # User Managemant
    path('accounts/', include('django.contrib.auth.urls')),

    # Local Apps
    path('accounts/', include('accounts.urls')),
    path('items/', include('items.urls', namespace='items')),
    path('', include('pages.urls', namespace='pages')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import (
    ItemListView,
    ItemDetailView,
    ItemUpdateView,
    ItemCreateView,
    ItemDeleteView,
)

app_name = 'items'


urlpatterns = [
    path('<uuid:pk>/update/', ItemUpdateView.as_view(), name='update'),
    path('<uuid:pk>/delete/', ItemDeleteView.as_view(), name='delete'),
    path('<uuid:pk>/', ItemDetailView.as_view(), name='detail'),
    path('new/', ItemCreateView.as_view(), name='create'),
    path('', ItemListView.as_view(), name='list'),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=15, null=True, blank=True)

items/models.py
import uuid
from django.db import models
from django.conf import settings
from django.urls import reverse
from .validators import validate_price


class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title


class Item(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    body = models.TextField(max_length=1000)
    price = models.CharField(max_length=10, validators=[validate_price])
    location = models.CharField(max_length=300)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    picture = models.ImageField(upload_to='pictures/', default='default.jpg')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('items:detail', args=[str(self.id)])

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

accounts/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

items/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Item


class ItemListView(ListView):
    model = Item
    queryset = Item.objects.all()
    template_name = 'items/list.html'


class ItemDetailView(DetailView):
    model = Item
    template_name = 'items/detail.html'


class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Item
    fields = ('title', 'body', 'price', 'category', 'location', 'picture')
    template_name = 'items/update.html'

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Item
    template_name = 'items/delete.html'
    success_url = reverse_lazy('items:list')

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    template_name = 'items/create.html'
    fields = ('title', 'body', 'price', 'category', 'location', 'picture',)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

pages/views.py
from django.urls import reverse_lazy
from django.views.generic import RedirectView


class HomePageView(RedirectView):
    url = reverse_lazy('items:list')

templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand m-0 p-0 mr-2" href="{% url 'items:list' %}">
            <img src="{% static 'images/logo.png' %}" width="40" height="40" alt="">
        </a>
        <a class="navbar-brand m-0 p-0 mr-3" href="{% url 'items:list' %}" style="font-weight: bold; font-size: 17pt;">SHOPPY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'items:list' %}">Products</a>
                </li>
            </ul>
            <ul class="navbar-nav">

                {% if user.is_authenticated %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle mr-2 text-dark" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>

                {% endif %}

                <li class="nav-item">
                    <a class="btn btn-outline-success" href="{% url 'items:create' %}">+ add item</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


    <link rel="stylesheet" href="{% static 'css/main.css' %}">

  {% block style %}{% endblock style %}

    <title>{% block title %}SHOPPY{% endblock title %}</title>
  </head>
  <body>
  {% include '_navbar.html' %}

  <div class="container mt-4">

  {% block content %}
  {% endblock content %}

  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  {% autoescape off %}
  {% block extra_js %}
  {% endblock extra_js %}
  {% endautoescape %}
  </body>
</html>

templates/items/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Item{% endblock title %}

{% block content %}
    <h2>Create Item</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Create</button>
    </form>
{% endblock content %}

templates/items/delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ object.title }}{% endblock title %}

{% block content %}
    <h2>Are you sure you want to delete this item?</h2>
    <div class="row">
    <div class="col-md-6">
    <div class="card">
        {% if object.pictures.all %}
            <img class="card-img-top" style="max-height: 250px; object-fit: cover;" src="{{ object.picture.url }}" alt="{{ object.title }}">
        {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text text-muted"><i class="far fa-list mr-2"></i>{{ object.category|truncatechars:40 }}<br>
                <i class="far fa-map-marker-alt mr-2 ml-1"></i>{{ object.location }}<br>
                    <span class="text-muted"><i class="far fa-clock mr-2"></i>{{ object.updated|date:'d M' }}</span><br>
                </p>
                <div class="text-right">
                <a href="{{ object.get_absolute_url }}" class="btn btn-light stretched-link align-right"><i style="font-size: 12pt;" class="far fa-dollar-sign"></i>{{ object.price }}</a>
                    </div>
            </div>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
    </form>
    </div>
{% endblock content %}

templates/items/detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}

<img class="img-thumbnail mb-2 mr-4 picture" src="{{ object.picture.url }}" alt="{{ post.title }}"
     style="height: 100%; width: 200pt; object-fit: cover;" xmlns="http://www.w3.org/1999/html">
{% if object.user == request.user %}
    <a class="btn btn-danger" href="{% url 'items:delete' object.id %}">Delete</a>
    <a class="btn btn-primary" href="{% url 'items:update' object.id %}">Edit</a>
    {% endif %}
    <h1>{{ object.title }}</h1>
    <hr>
    <div class="row">
    <div class="col-md-4">
        <p><i class="far fa-list mr-2"></i>{{ object.category|truncatechars:40 }}</p>
    <p><i class="far fa-map-marker-alt mr-2 ml-1"></i>{{ object.location }}</p>
    </div>
    <div class="col-md-4">
        <p><i class="far fa-clock mr-2"></i><span id="email">{{ object.updated|date:'d M' }}</span></p>
        <p><i class="far fa-user mr-2"></i><span id="phone">{{ object.user.username }}</span></p>
    </div>
    <div class="col-md-4">
        <p><i class="far fa-envelope-open mr-2"></i>{{ object.user.email }}</p>
        {% if object.user.phone %}
        <p><i class="far fa-phone mr-2"></i>{{ object.user.phone }}</p>
        {% endif %}
    </div>
    </div>
    <p>{{ object.body }}</p>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/items/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}List of Items{% endblock title %}

{% block content %}
<div class="card-columns">
    {% for object in object_list %}
        <div class="card">
        {% if object.picture %}
            <img class="card-img-top" style="max-height: 250px; object-fit: cover;" src="{{ object.picture.url }}" alt="{{ object.title }}">
        {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text text-muted"><i class="far fa-list mr-2"></i>{{ object.category|truncatechars:40 }}<br>
                <i class="far fa-map-marker-alt mr-2 ml-1"></i>{{ object.location }}<br>
                    <span class="text-muted"><i class="far fa-clock mr-2"></i>{{ object.updated|date:'d M' }}</span><br>
                </p>
                <div class="text-right">
                <a href="{{ object.get_absolute_url }}" class="btn btn-light stretched-link align-right"><i style="font-size: 12pt;" class="far fa-dollar-sign"></i>{{ object.price }}</a>
                    </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

templates/items/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit {{ object.title }}{% endblock title %}

{% block content %}
    <h2>Edit post</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Edit</button>
    </form>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}SHOPPY{% endblock title %}

{% block content %}
    HI {{ request.user }}!
{% endblock content %}